Repository selsa-inube/inubekit-blanket, pull requests merged in 2024-03, with the labels that each got.

#2 Refactor components to use new token structure
  package-lock.json
  package.json
  src/Blanket/index.tsx
  src/Blanket/stories/Blanket.stories.tsx
  src/Blanket/stories/styles.js
  src/Blanket/styles.js
  vite.config.ts
Labels: major

#3 Publish new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#4 Adjust and export interfaces
  src/index.ts
Labels: minor

#5 Update inubekit/blanket to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#6 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
